services:
  # --- Backend PHP-FPM ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
      - ./backend/.env:/var/www/html/.env 
    command: >
      sh -c "until nc -z db 3306; do echo 'Waiting for MySQL...'; sleep 2; done &&
              php artisan config:clear && 
              (php artisan key:generate || true) &&
              php-fpm"
    networks:
      - app_network
    depends_on:
      - db

  # --- Backend Nginx ---
  backend_nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "8000:80"

  # --- Frontend Vue ---
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vue_app
    depends_on:
      - backend_nginx
    networks:
      - app_network
    ports:
      - "8080:80"

  # --- Base de datos ---
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
      wait_timeout: 28800
      interactive_timeout: 28800
      max_allowed_packet: 256M
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=28800 --interactive_timeout=28800 --max_allowed_packet=256M
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app_network
    ports:
      - "3308:3306" # Puerto externo 3308 mapeado al interno 3306

volumes:
  db_data:

networks:
  app_network:
    driver: bridge